image: mcr.microsoft.com/dotnet/sdk:latest

stages:
    - build
    - test
    - deploy

variables:
    solution: "Core.sln"
    configuration: "Release"
    version: "1.0.0"

build-job:
    stage: build
    script:
        - echo "Restore solution ..."
        - "dotnet restore $solution -p:Configuration=$configuration"
        - echo "Building solution ..."
        - "dotnet build $solution -p:Configuration=$configuration -p:Version=$version -p:GeneratePackageOnBuild='false' --no-restore"
        - echo "Creating nuget packages ..."
        - "dotnet pack $solution -p:Configuration=$configuration -p:Version=$version --no-build"
    artifacts:
        paths:
        - assemblies
        - nuget

unit-test-job:
    stage: test
    script:
        - echo "Executing unit tests ..."
        - "dotnet test $solution"

publish-job:
    stage: deploy
    script:
        - echo "Publishing nuget packages ..."
        - dotnet nuget add source "${CI_API_V4_URL}/projects/5/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
        - dotnet nuget push "nuget/*.nupkg" --source gitlab
    
        
