image: microsoft/dotnet:latest

stages:
    - build
    - test

variables:
    solution: "Core.sln"

before_script:
    - "dotnet restore $solution"

build:
    stage: build
    script:
        - "dotnet build $solution"