image: microsoft/dotnet:latest

stages:
    - build
    - test

variables:
    solution: "Core.sln"
    configuration: "Release"
    framework: "netstandard2.0"
    version: "1.0.0"

build:
    stage: build
    artifacts:
        paths:
        - assemblies
        - nuget
    script:
        - "dotnet build $solution -c $configuration -f $framework -p:Version=$version"