image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - test

variables:
    solution: "Core.sln"
    configuration: "Release"
    version: "1.0.0"

build:
    stage: build
    artifacts:
        paths:
        - nuget
    script:
        - "dotnet build $solution -c $configuration -p:Version=$version"