language: csharp
solution: Core.sln
install:
  - nuget restore Core.sln
script:
  - msbuild /p:Configuration=Release Core.sln
  - nuget.exe setApiKey $NUGET_API_KEY -Source $NUGET_SOURCE -Verbosity quiet
  - nuget.exe push ./nuget/*.nupkg -Source $NUGET_SOURCE